version: "3.7"

services:
  db:
    image: mysql:8.0
    networks:
      - keek_internal
    environment:
      - MYSQL_ROOT_PASSWORD=Keek@Root2025
      - MYSQL_DATABASE=keekconecta
      - MYSQL_USER=keek
      - MYSQL_PASSWORD=Keek@DB2025
      - TZ=America/Sao_Paulo
    volumes:
      - keek_db:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "1"
          memory: 512M

  app:
    image: adrielferr/parlamentares:latest
    networks:
      - network_public
      - keek_internal
    environment:
      - DB_HOST=db
      - DB_NAME=keekconecta
      - DB_USER=keek
      - DB_PASS=Keek@DB2025
      - CRYPTO_KEY=c3509b281e51bb4443f4db3cbdb65ca695a152f5e4125de482d80c349bfe4d25
      - APP_URL=https://parlamentares.keekconecta.com.br
      - BASE_PATH=
      - ADMIN_EMAIL=adriel@keekconecta.com.br
      - ADMIN_PASS=Keek@Admin2025
      - TZ=America/Sao_Paulo
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - traefik.enable=1
        - traefik.http.routers.keekconecta.rule=Host(`parlamentares.keekconecta.com.br`)
        - traefik.http.routers.keekconecta.entrypoints=websecure
        - traefik.http.routers.keekconecta.priority=1
        - traefik.http.routers.keekconecta.tls.certresolver=letsencryptresolver
        - traefik.http.routers.keekconecta.service=keekconecta
        - traefik.http.services.keekconecta.loadbalancer.server.port=80
        - traefik.http.services.keekconecta.loadbalancer.passHostHeader=true
        - traefik.http.services.keekconecta.loadbalancer.sticky.cookie=true
        - traefik.http.services.keekconecta.loadbalancer.sticky.cookie.name=KKSESSION
      resources:
        limits:
          cpus: "1"
          memory: 512M

volumes:
  keek_db:

networks:
  network_public:
    external: true
    name: network_public
  keek_internal:
    driver: overlay
