-- Edidesk schema
CREATE DATABASE IF NOT EXISTS keekconecta CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE keekconecta;

CREATE TABLE IF NOT EXISTS clientes (
  id        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome      VARCHAR(200) NOT NULL,
  ativo     TINYINT(1) NOT NULL DEFAULT 1,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS usuarios (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT UNSIGNED NULL,
  nome       VARCHAR(200) NOT NULL,
  email      VARCHAR(200) NOT NULL UNIQUE,
  senha_hash VARCHAR(255) NOT NULL,
  nivel      TINYINT(1) NOT NULL DEFAULT 4 COMMENT '0=SuperAdmin,1=ClienteAdmin,2=Gestor,3=Analista,4=Visualizador',
  ativo      TINYINT(1) NOT NULL DEFAULT 1,
  criado_em  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fontes_legislativas (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source_key VARCHAR(50) NOT NULL UNIQUE,
  label      VARCHAR(200) NOT NULL,
  url        VARCHAR(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projetos (
  id             INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cliente_id     INT UNSIGNED NOT NULL,
  fonte_id       INT UNSIGNED NULL,
  nome           VARCHAR(200) NOT NULL,
  openai_key_enc TEXT NULL COMMENT 'AES-256-CBC encrypted',
  parl_total     INT UNSIGNED NOT NULL DEFAULT 0,
  ativo          TINYINT(1) NOT NULL DEFAULT 1,
  criado_em      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
  FOREIGN KEY (fonte_id)   REFERENCES fontes_legislativas(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sentinela_conversas (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  projeto_id  INT UNSIGNED NOT NULL,
  usuario_id  INT UNSIGNED NOT NULL,
  pergunta    TEXT NOT NULL,
  resposta    TEXT NOT NULL,
  criado_em   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (projeto_id) REFERENCES projetos(id) ON DELETE CASCADE,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sentinela_arquivos (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  projeto_id INT UNSIGNED NOT NULL,
  nome       VARCHAR(300) NOT NULL,
  conteudo   MEDIUMTEXT NOT NULL,
  ativo      TINYINT(1) NOT NULL DEFAULT 1,
  criado_em  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (projeto_id) REFERENCES projetos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS parlamentares_cache (
  id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source_key   VARCHAR(50) NOT NULL,
  sapl_id      INT UNSIGNED NOT NULL,
  dados_json   MEDIUMTEXT NOT NULL,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_source_sapl (source_key, sapl_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
